language: java
jdk:
  - oraclejdk8
install: "mvn install -DskipTests"
script: "ulimit -s 1082768 ; mvn -e clean verify jacoco:report coveralls:report"

addons:
  sonarqube:
    organization: "uweschaefer-github"
    