databaseChangeLog:
  - changeSet:
      id: issue372
      author: akp
      changes:
        - sql:
          endDelimiter: \nGO
          splitStatements: true
          sql: CREATE USER "factcastApplicationUser" NOLOGIN;
               GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE tokenstore, catchup TO "factcastApplicationUser";
               GRANT SELECT, INSERT,         UPDATE ON TABLE fact TO "factcastApplicationUser";
               GRANT EXECUTE ON FUNCTION notifyFactInsert() TO "factcastApplicationUser";
               GRANT USAGE,SELECT ON SEQUENCE catchup_seq, fact_ser_seq TO "factcastApplicationUser";
               
