databaseChangeLog:
  - changeSet:
      id: issue372
      author: akp
      changes:
        - sql:
          endDelimiter: \nGO
          splitStatements: true
          sql: CREATE USER "factcast-application-user" NOLOGIN;
               GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE tokenstore, catchup TO "factcast-application-user";
               GRANT SELECT, INSERT,         UPDATE ON TABLE fact TO "factcast-application-user";
               GRANT EXECUTE ON FUNCTION notifyFactInsert() TO "factcast-application-user";
               GRANT USAGE,SELECT ON SEQUENCE catchup_seq, fact_ser_seq TO "factcast-application-user";
               
